parking_node:
 ros__parameters:      

  # max/min values 
    ci_steering_straight_p:  1.0
    ci_steering_left_p:  0.0
    ci_steering_right_p:  1.8
    ci_speed_stop_p:  1.0
    ci_speed_forward_p:  1.02
    ci_speed_reverse_p:  0.98
    ci_distance_forward_single_step_p:  .100
    ci_distance_reverse_single_step_p:  .100
    ci_distance_reverse_p:  5.000
    ci_distance_forward_p:  5.000
    ci_lidar_angle_offset_p: 0.0
    ci_wall_distance_p: 0.95

  # conditions to perform reverse right move at start  //single move maneuver
    REVERSE_RIGHT_imu_min_p:  76.
    REVERSE_RIGHT_imu_max_p:  95.
    REVERSE_RIGHT_lidar_p:  0.
    REVERSE_RIGHT_us_left_p:  .15
    REVERSE_RIGHT_us_right_p: .2
    REVERSE_RIGHT_us_rear_left_p:  .2
    REVERSE_RIGHT_us_rear_right_p:  .2
    REVERSE_RIGHT_us_front_left_p:  -1.
    REVERSE_RIGHT_us_front_right_p:  -1.
    REVERSE_RIGHT_previous_state_p:  -1
    REVERSE_RIGHT_distance_p:  1.300

      # conditions to perform reverse left  move anytime
    REVERSE_LEFT_imu_min_p:  -10.
    REVERSE_LEFT_imu_max_p:  10.
    REVERSE_LEFT_lidar_p:  0.
    REVERSE_LEFT_us_left_p:  .2
    REVERSE_LEFT_us_right_p: .15
    REVERSE_LEFT_us_rear_left_p:  -1.
    REVERSE_LEFT_us_rear_right_p:  -1.
    REVERSE_LEFT_us_front_left_p:  -1.
    REVERSE_LEFT_us_front_right_p:  -1.
    REVERSE_LEFT_previous_state_p:  6
    REVERSE_LEFT_distance_p:  .2   

  # conditions to perform reverse straight correction move anytime
    REVERSE_STRAIGHT_imu_min_p:  -10.
    REVERSE_STRAIGHT_imu_max_p:  10.
    REVERSE_STRAIGHT_lidar_p:  0.
    REVERSE_STRAIGHT_us_left_p:  .15
    REVERSE_STRAIGHT_us_right_p: .15
    REVERSE_STRAIGHT_us_rear_left_p: .22
    REVERSE_STRAIGHT_us_rear_right_p:  .22
    REVERSE_STRAIGHT_us_front_left_p:  -1.
    REVERSE_STRAIGHT_us_front_right_p:  -1.
    REVERSE_STRAIGHT_previous_state_p:  6
    REVERSE_STRAIGHT_distance_p:  -.23   

  # conditions to perform forward left correction move anytime
    FORWARD_LEFT_imu_min_p:  -10.
    FORWARD_LEFT_imu_max_p:  90.
    FORWARD_LEFT_lidar_p:  0.
    FORWARD_LEFT_us_left_p:  -1.
    FORWARD_LEFT_us_right_p: .6
    FORWARD_LEFT_us_rear_left_p:  .150
    FORWARD_LEFT_us_rear_right_p:  .150
    FORWARD_LEFT_us_front_left_p:  .50
    FORWARD_LEFT_us_front_right_p:  .50
    FORWARD_LEFT_previous_state_p:  -1
    FORWARD_LEFT_distance_p:  0.42

  # conditions to perform forward right correction move anytime
    FORWARD_RIGHT_imu_min_p:  -10.
    FORWARD_RIGHT_imu_max_p:  10.
    FORWARD_RIGHT_lidar_p:  0.
    FORWARD_RIGHT_us_left_p:  -1.
    FORWARD_RIGHT_us_right_p: .14
    FORWARD_RIGHT_us_rear_left_p:  -1.
    FORWARD_RIGHT_us_rear_right_p:  -1.
    FORWARD_RIGHT_us_front_left_p:  .2
    FORWARD_RIGHT_us_front_right_p:  .2
    FORWARD_RIGHT_previous_state_p:  6
    FORWARD_RIGHT_distance_p:  .200

    
  # conditions to perform forward straight correction move anytime
    FORWARD_STRAIGHT_imu_min_p:  -10.
    FORWARD_STRAIGHT_imu_max_p:  10.
    FORWARD_STRAIGHT_lidar_p:  0.
    FORWARD_STRAIGHT_us_left_p:  .15
    FORWARD_STRAIGHT_us_right_p: .15
    FORWARD_STRAIGHT_us_rear_left_p:  -1.
    FORWARD_STRAIGHT_us_rear_right_p:  -1.
    FORWARD_STRAIGHT_us_front_left_p:  .1
    FORWARD_STRAIGHT_us_front_right_p: .1
    FORWARD_STRAIGHT_previous_state_p:  6
    FORWARD_STRAIGHT_distance_p:  .50  

 # conditions for start
    START_imu_min_p:  -1.
    START_imu_max_p:  -1.
    START_lidar_p:  -1.
    START_us_left_p:  0.140
    START_us_right_p: 0.140
    START_us_rear_left_p:  0.050
    START_us_rear_right_p:  0.050
    START_us_front_left_p:  0.050
    START_us_front_right_p:  0.050
    START_previous_state_p:  -1
    START_distance_p: -0.35       

 # conditions for stop
    STOP_imu_min_p:  -1.
    STOP_imu_max_p:  -1.
    STOP_lidar_p:  -1.
    STOP_us_left_p:  0.140
    STOP_us_right_p: 0.140
    STOP_us_rear_left_p:  0.07
    STOP_us_rear_right_p:  0.070
    STOP_us_front_left_p:  0.10
    STOP_us_front_right_p:  0.10
    STOP_previous_state_p:  -1
    STOP_distance_p: -1.   

  # conditions for finish
    FINISH_imu_min_p:  85.0
    FINISH_imu_max_p:  95.0
    FINISH_lidar_p:  -1.
    FINISH_us_left_p:  .15
    FINISH_us_right_p: .15
    FINISH_us_rear_left_p:  .2
    FINISH_us_rear_right_p:  .2
    FINISH_us_front_left_p:  -1.
    FINISH_us_front_right_p:  -1.
    FINISH_previous_state_p:  -1
    FINISH_distance_p: -1.               